server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html

aws:
  sqs:
    gca-ingestion-url: "https://sqs.eu-west-2.amazonaws.com/394431749443/gca-ingestion-event"
  s3:
    ingestion-bucket: "gca-ingestion"
  sns:
    ingestion-topic: "arn:aws:sns:eu-west-2:394431749443:gca-ingestion-topic"
